export { default as Affirmation } from './Affirmation'
export { default as CreditCard } from './CreditCard'
export { default as FreePlan } from './FreeTrial'
export { default as HomePage } from './Home'
export { default as PlanSetup } from './PlanSetup'
export { default as ResetPassword } from './ResetPassword'
export { default as Verification } from './Verification'
export { default as IntroSetup } from './IntroSetup'
export { default as AllSet } from './Affirmation/AllSet'
export { default } from './UserSetup'
